---
- name: Set config_root
  set_fact:
    config_root: "/etc/pes/{{ container_env_prefix }}"

- name: Create configs directory
  file:
    name: "{{ config_root }}"
    state: directory
    mode: '0755'

- name: Create db directory
  file:
    name: "{{ config_root }}/data"
    state: directory
    mode: '0755'

- name: Add repository "docker-ce"
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    owner: root
    mode: 0644
    force: yes

- name: Install dnf packages
  dnf:
    name: "{{ dnf_packages }}"
    state: present

- name: Install python docker SDK
  pip:
    name:
      - docker
    state: present

- name: Enable and start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Sysctl option `net.core.somaxconn`
  sysctl:
    name: "net.core.somaxconn"
    value: "65535"
    state: present
    sysctl_set: yes
    reload: yes
