---
- name: Send files
  synchronize:
    src: "{{ item }}"
    dest: "{{ source_path }}"
    rsync_opts:
      - "--exclude=.venv"
  with_items:
    - "../../../ci"
    - "../../../src"

- name: Restart backend docker container
  docker_container:
    name: "{{ container_env_prefix }}_backend"
    restart: yes
  tags:
    - never
    - deploy_files
