---

- name: Add backend docker network
  docker_network:
    name: backend

- name: Add public docker network
  docker_network:
    name: public
    driver: bridge

- name: Auth in Docker registry
  docker_login:
    username: soksanichenko
    password: "{{ docker_hub_token }}"
