---

- name: Get state of previous migration
  stat:
    path: "{{ config_root }}/.db_is_migrated"
  register: db_is_migrated

- name: Migration from SQLite to PostgreSQL
  block:
    - name: Sleep before migration
      wait_for:
        timeout: 15

    - name: Run pqloader
      community.docker.docker_container_exec:
        container: "{{ container_env_prefix }}_postgres"
        command: 'pgloader /migration_scenario'

    - name: Set state of current migration
      file:
        path: "{{ config_root }}/.db_is_migrated"
        state: touch
  when: db_is_migrated is defined and not db_is_migrated.stat.exists
