---

- name: Install certbot package
  yum:
    name:
      - certbot
    enablerepo: epel

- name: Create acme directory
  file:
    name: "{{ config_root }}/acme/"
    state: directory
    mode: '0755'

- name: Obtain certificate first time
  systemd:
    name: "certbot.service"
    state: restarted

- name: Prepare nginx configuration with SSL
  template:
    src: nginx.conf.j2
    dest: "{{ config_root }}/nginx.conf"
    owner: root
    group: root
    mode: '0644'

- name: Restart the nginx container
  docker_container:
    name: "{{ container_env_prefix }}_nginx"
    restart: yes

