FROM python:3 AS python39-uwsgi
RUN apt-get install -y libpq-dev
COPY requirements.txt requirements.txt
RUN pip install -U -r requirements.txt

WORKDIR /src/app

# Add webserver user
RUN useradd webserver

COPY start.sh /start.sh
RUN chmod +x /start.sh
ENTRYPOINT /start.sh